/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package saludconecta;

import conexion.CONEXION;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
/**
 *
 * @author LENOVO
 */
public class personales extends javax.swing.JPanel {

    /**
     * Creates new form personales
     */
   
    public personales() {
        initComponents();
        txtnombres.setText(Integer.toString(login.idempleado));
        cargarDatosEmpleado(login.idempleado);
    }
// Suponiendo que tienes un método que obtiene la conexión y que login.idempleado contiene el id del empleado

public void cargarDatosEmpleado(int idEmpleado) {
    String query = "SELECT e.empleado_CURP, e.empleado_nombre, e.empleado_paterno, e.empleado_materno, " +
                   "e.empleado_tel, e.empleado_fechaNacimiento, e.empleado_sueldo, e.fechaInicio, e.fechaFin, " +
                   "d.calle, d.numero, d.colonia, d.codigoPostal, " +
                   "h.horario_turno, h.horario_inicio, h.horario_fin " +
                   "FROM [CMZ_BETA].[dbo].[Empleado] e " +
                   "JOIN [CMZ_BETA].[dbo].[Direccion] d ON e.id_direccion = d.id_Direccion " +
                   "JOIN [CMZ_BETA].[dbo].[Horario] h ON e.id_horario = h.id_horario " +
                   "WHERE e.id_empleado = ?";

    Connection con = null;
    PreparedStatement ps = null;
    ResultSet rs = null;

    try {
        con = CONEXION.obtenerConexion();
        if (con != null) {
            ps = con.prepareStatement(query);
            ps.setInt(1, idEmpleado);
            rs = ps.executeQuery();

            if (rs.next()) {
                txtcurp.setText(rs.getString("empleado_CURP"));
                txtnombres.setText(rs.getString("empleado_nombre"));
                txtpaterno.setText(rs.getString("empleado_paterno"));
                txtmaternos.setText(rs.getString("empleado_materno"));
                txttelefono.setText(rs.getString("empleado_tel"));
                txtnacimiento.setText(rs.getString("empleado_fechaNacimiento"));
                txtsueldo.setText(rs.getString("empleado_sueldo"));
                txtinicio.setText(rs.getString("fechaInicio"));
                txtdireccion.setText(rs.getString("calle"));
                txtnumero.setText(rs.getString("numero"));
                txtcolonia.setText(rs.getString("colonia"));
                txtpostal.setText(rs.getString("codigoPostal"));
                txtturno.setText(rs.getString("horario_turno"));
                txthorarioinicio.setText(rs.getString("horario_inicio"));
                txthorariofin.setText(rs.getString("horario_fin"));
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron datos para el empleado con ID: " + idEmpleado);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al conectar a la base de datos.");
        }
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error al realizar la consulta.");
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (con != null) con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}

// Llamar al método con el id del empleado, por ejemplo:
// cargarDatosEmpleado(login.idempleado);

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcurp = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtpaterno = new javax.swing.JTextField();
        txthorariofin = new javax.swing.JTextField();
        txtpostal = new javax.swing.JTextField();
        txtsueldo = new javax.swing.JTextField();
        txtnacimiento = new javax.swing.JTextField();
        txttelefono = new javax.swing.JTextField();
        txtinicio = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtnumero = new javax.swing.JTextField();
        txtcolonia = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtmaternos = new javax.swing.JTextField();
        txtturno = new javax.swing.JTextField();
        txthorarioinicio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(65, 70, 76));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Datos personales");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addContainerGap(947, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        txtcurp.setBorder(javax.swing.BorderFactory.createTitledBorder("Curp"));
        jPanel1.add(txtcurp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 310, 53));

        txtnombres.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombres"));
        jPanel1.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 310, 53));

        txtpaterno.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos Paterno"));
        jPanel1.add(txtpaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 310, 53));

        txthorariofin.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario fin"));
        jPanel1.add(txthorariofin, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 510, 310, 53));

        txtpostal.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion codigo postal"));
        jPanel1.add(txtpostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 310, 53));

        txtsueldo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sueldo"));
        jPanel1.add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, 310, 53));

        txtnacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de nacimiento"));
        jPanel1.add(txtnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 310, 53));

        txttelefono.setBorder(javax.swing.BorderFactory.createTitledBorder("Telefono"));
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 310, 53));

        txtinicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de trabajo"));
        jPanel1.add(txtinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 350, 310, 53));

        txtdireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(" Direccion calle"));
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 310, 53));

        txtnumero.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion numero"));
        jPanel1.add(txtnumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 190, 310, 53));

        txtcolonia.setBorder(javax.swing.BorderFactory.createTitledBorder("Direccion colonia"));
        jPanel1.add(txtcolonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 310, 53));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 1130, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 20, 420));

        txtmaternos.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellidos Maternos"));
        jPanel1.add(txtmaternos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 310, 53));

        txtturno.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario turno"));
        jPanel1.add(txtturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 310, 53));

        txthorarioinicio.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario inicio"));
        jPanel1.add(txthorarioinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 310, 53));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 1130, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 824, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField txtcolonia;
    private javax.swing.JTextField txtcurp;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txthorariofin;
    private javax.swing.JTextField txthorarioinicio;
    private javax.swing.JTextField txtinicio;
    private javax.swing.JTextField txtmaternos;
    private javax.swing.JTextField txtnacimiento;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtnumero;
    private javax.swing.JTextField txtpaterno;
    private javax.swing.JTextField txtpostal;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txtturno;
    // End of variables declaration//GEN-END:variables
}
